### ISSUE TITLE
Fatal error: Call to undefined function install_display_output() 

### ISSUE THREAD

**Issue by tormi** [pantheon-systems/drops-8#58] opened 2015-08-20 14:24 UTC
Fatal error: Call to undefined function install_display_output() in /core/includes/errors.inc on line 240 after accepting #51.

**Comment by greg-1-anderson** [comment] 2015-08-20 17:27
Okay, this **did** happen to me yesterday, but I did not notice, because even though the above error appeared in my Error log on my dashboard, Drupal 8 installed just fine.

Today, I get a 500 error when I attempt to install Drupal 8, **and** the above error is in my log.

**WORKAROUND:**  Go directly to `core/install.php`, and your site will install.

I will continue to look into these problems, though.

**Comment by greg-1-anderson** [comment] 2015-08-24 23:29
@tormi: Did you see this when upgrading an existing site, or was this a fresh install?

**Comment by tormi** [comment] 2015-08-25 06:22
On upgrading, site `e55023a0-ee39-4813-962a-f59b89697994` dev for example.

**Comment by greg-1-anderson** [comment] 2015-08-25 22:03
This happens when someone calls `_drupal_log_error()` after `$GLOBALS['install_state']` is set, but before `install.core.inc` is included (because that is where this function is defined).

The typical place where $install_state is initialized is inside `install.core.inc`, so it is expected that this situation ($install_state set before install_display_output() defined) should never arise.

On a fresh install, this error is not displayed until you visit the site for the first time. The error occurs every time you visit your site prior to installing it.  The error does not occur if you go directly to core/install.php.

Seems this is caused by something done in our redirect logic.  I expect this should go away naturally when we fix #3, so closing as a duplicate.

**Comment by greg-1-anderson** [comment] 2015-08-25 22:09
Wait, not quite related.  It is this, from our settings.pantheon.inc file:
```
/**
 * Override the $install_state variable to let Drupal know that the settings are verified
 * since they are being passed directly by the Pantheon.
 *
 * Issue: https://github.com/pantheon-systems/drops-8/issues/9
 *
 */
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  $GLOBALS['install_state']['settings_verified'] = TRUE;
}
```

**Comment by greg-1-anderson** [comment] 2015-08-27 17:50
This PR is included in the commits from the new reduced repository.  See #50.

**Closed by greg-1-anderson** 2015-08-27 17:50 UTC
Labels: minor
