### ISSUE TITLE
Cannot re-install Drupal 8

### ISSUE THREAD

**Issue by akalata** [pantheon-systems/drops-8#47] opened 2015-07-17 14:30 UTC
I just created a Drupal 8 beta site (5e178f5e-36bb-4f96-9b29-02bc72598cd8). I added a custom install profile to the repo and am attempting to re-install with that profile. During install I get the following errors:

    Warning: file_put_contents(/srv/bindings/dc5d5b0332b24f779b180a2ea275c7db/code/sites/default/settings.php): failed to open stream: Permission denied in drupal_rewrite_settings() (line 318 of core/includes/install.inc).

    drupal_rewrite_settings(Array)
    install_write_profile(Array)
    install_run_task(Array, Array)
    install_run_tasks(Array)
    install_drupal(Object)

    Exception: Failed to modify <em class="placeholder">sites/default/settings.php</em>. Verify the file permissions. in drupal_rewrite_settings() (line 319 of core/includes/install.inc).

    drupal_rewrite_settings(Array)
    install_write_profile(Array)
    install_run_task(Array, Array)
    install_run_tasks(Array)
    install_drupal(Object)

**Comment by illepic** [comment] 2015-07-18 19:34
Noting here that the same error happens when "Wiping" dev to start over from scratch: We can make it through the install step of choosing the "Standard" install profile, but then the above error occurs.

**Comment by asentner** [comment] 2015-07-19 14:51
While this is a problem Pantheon needs to work out, the work around for anyone who is stuck is to SFTP to the environment with SFTP mode enabled in your dashboard and run the command:

```
chmod 666 code/sites/default/settings.php
```

**Comment by greg-1-anderson** [comment] 2015-08-10 20:04
Duplicate of #36

**Closed by greg-1-anderson** 2015-08-10 20:04 UTC
