### ISSUE TITLE
Selecting non-English language during installation results in redirect Loop

### ISSUE THREAD

**Issue by heddn** [pantheon-systems/drops-8#21] opened 2014-11-15 12:37 UTC
This was working on beta-2, but when I went to install beta-3, selecting Spanish or any other language than English resulted in a redirect loop. I can locally install beta-3, so this must be issue on the pantheon environment.

**Comment by populist** [comment] 2015-04-01 23:08
I can confirm this is still an issue with the latest beta. Will need additional research.

**Comment by populist** [comment] 2015-05-06 00:45
I can confirm this is still an issue with the latest beta (Drupal 8 Beta 10) and will need additional research into what is going on. Probably the result of the craziness with our redirect logic in settings.php (https://github.com/pantheon-systems/drops-8/blob/master/sites/default/settings.php).

**Comment by heddn** [comment] 2015-05-08 18:12
Also possibly related to https://www.drupal.org/node/1338384 & https://www.drupal.org/node/2474537

**Comment by greg-1-anderson** [comment] 2015-08-10 20:09
Running `drush site-install` also produces some garbage output about a redirect (to the shell); I believe this is also related to our `install_goto('core/install.php');` in settings.php, which is probably the root cause of this issue.

**Comment by tormi** [comment] 2015-08-12 17:43
Similar problems when trying to activate language switch block:
`<em class="placeholder">Recoverable fatal error</em>: Argument 1 passed to Drupal\Core\Language\Language::Drupal\Core\Language\{closure}() must implement interface Drupal\Core\Language\LanguageInterface, null given funktsioonis <em class="placeholder">Drupal\Core\Language\Language::Drupal\Core\Language\{closure}()</em> (rida <em class="placeholder">159</em> / <em class="placeholder">/htdocs/core/lib/Drupal/Core/Language/Language.php</em>).`

**Comment by greg-1-anderson** [comment] 2015-08-12 20:45
I was able to install Drupal with an Esparanto locale using #53.

**Comment by greg-1-anderson** [comment] 2015-08-20 17:49
Fixed with the release of Drupal 8.0.0-beta14

**Closed by greg-1-anderson** 2015-08-20 17:49 UTC
