### ISSUE TITLE
Installation with Italian language produces redirect loop on install

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/drops-8#94] opened 2015-10-13 13:15 UTC
https://youtu.be/Uyjic-DfY00

Site:
http://dev-d8rc1-oct13-italian.pantheon.io

Dash:
https://dashboard.getpantheon.com/sites/08863efa-5863-44ee-9eec-84e571537425#dev/code

Url on redirect page
http://dev-d8rc1-oct13-italian.pantheon.io/core/install.php?langcode=it

WORKAROUND:

Click the reload button on the error page and continue with site setup.
https://www.evernote.com/l/AhUBtv1-Re9GnJokrxK78hIsb8lXxQ7Yl3Y

**Comment by greg-1-anderson** [comment] 2015-10-13 15:56
Can't reproduce this with another site. Can I wipe this one, and install again?

I might understand if this was an upgrade from an earlier beta, but it looks like you created it fresh.  I do not get a redirect loop when I create a new d8rc1 site, and install with an alternate translation.

**Comment by greg-1-anderson** [comment] 2015-10-13 16:29
If I wipe the site and go directly to:

http://dev-d8rc1-oct13-italian.pantheon.io/core/install.php?langcode=it

Then my web browser reports a redirect loop, and, after a short pause, then proceeds on to the correct page.

**Comment by greg-1-anderson** [comment] 2015-10-13 16:34
It behaves the same way if I allow it to redirect to core/install.php, and then select a translation.

Maybe this is "correct" behavior for Drupal--it keeps redirecting to the same URL until the translation finishes downloading, and sometimes the browser predicts the redirect is infinite, when in fact it will eventually complete?  Just a theory at this point.  Using Chrome.

**Comment by greg-1-anderson** [comment] 2015-10-13 19:25
In a local Apache install (with mod rewrite disabled), the sequence is:
```
302 core/install.php?langcode=it
200 core/install.php?langcode=it
```
That is, there is a single redirect, then the next page is displayed. Note that with mod rewrite enabled, the final URL is `core/install.php?rewrite=ok&langcode=it`; I disabled mod rewrite in case that made a difference.

When the problem occurs on Pantheon, there are many occurrences of the redirect, until it works. I am now seeing the error on Firefox as well.

Adding the pre-initialization code from settings.pantheon.inc to my local Apache site did not cause the problem to happen locally, so this seems unrelated to #77.

**Comment by greg-1-anderson** [comment] 2015-10-13 19:30
Also unrelated to #80, and unrelated to #21 / #53.

**Comment by greg-1-anderson** [comment] 2015-10-13 19:33
Also, once the browser successfully displays the "select installation profile" page for a given language once, it always gets there successfully on every subsequent attempt (until you wipe the site, erasing the downloaded translation). So, the code path that determines that the translation file has already been downloaded works, and the code path the downloads the translation file will sometimes fail.

**Comment by greg-1-anderson** [comment] 2015-10-14 00:10
Tried this on 8.0.0-beta12, and got the same error. Don't remember seeing this previously; influenced by something in the platform, maybe?  Most of my installs were in English; if you look away and do not see the "redirect loop" page, it reloads and fixes itself, so I might have simply missed it. Pretty sure I didn't just miss it when I could not reproduce this morning, but this evening I've never seen in install where it did _not_ happen.

Comparing the execution path of the local Apache install (working) vs. the Pantheon install (with redirect loop), the behavior is nearly identical. 

(1) Both pass successfully through install_download_translation(), and redirect with $install_state['translations'][$langcode] = TRUE;.  

(2) Next, install_select_profile() is called, but $install_state['translations'][$langcode] is still TRUE, so another redirect happens.

(3) Finally, install_select_profile() is called again, but this time $install_state['translations'][$langcode] holds a string that points to the translation file that was downloaded, and the profile-selection dialog is displayed.

In the working case, these steps happen without any preamble.  In the Pantheon case, step (2) results in a redirect loop. The web browser stops the redirect loop after a half-dozen iterations or so, and reports a failure; after a brief pause, the web browser (Chrome) reloads the same URL, but this time $install_state['translations'][$langcode] is correctly initialized, and the dialog is displayed. The handling of the translations and the redirects all happens in install_get_form(), which relies completely on Drupal 8's form handlers.

**Comment by greg-1-anderson** [comment] 2015-10-14 21:24
As near as I can tell, the code paths and all variable values in Drupal in the working and non-working cases are exactly the same. Seems like there must be something purely in the Pantheon platform that is causing this. Sounds unlikely, but that seems to be what the evidence is pointing to.

**Comment by primerg** [comment] 2015-10-15 06:12
Using the d8-rc1, it worked for me http://screencast.com/t/oXEJmhRe1OW

**Comment by greg-1-anderson** [comment] 2015-10-15 17:37
I looked at this with @davidstrauss this morning. My current experience is that I **cannot** reproduce this with Chrome, but I **can** reproduce it 100% of the time with Firefox.  When we went straight to the application server, bypassing the varnish cache, using Firefox, it worked.

Next I will try without browser extensions, in case they have some effect on the behavior.

**Comment by greg-1-anderson** [comment] 2015-10-15 17:51
Still fails in Firefox with all plugins disabled.

**Comment by greg-1-anderson** [comment] 2015-10-15 23:22
Cannot reproduce on a f22 onebox. Perhaps this will fix itself once the OS upgrade has been fully rolled out.

**Comment by greg-1-anderson** [comment] 2015-10-16 00:38
@kibra migrated Styx on my test site from an f20 box to an f22 box, and I can no longer reproduce this issue.  Perhaps we should just wait ~1wk for the migration to be complete, and see if this just goes away.

**Comment by greg-1-anderson** [comment] 2015-10-16 01:18
@kibra confirmed that this happens because Varnish 3 (used on f20 systems) caches the 302 redirect, and re-serves it on subsequent requests. This was fixed in Varnish 4 (used on f22 systems), when [Varnish started respecting the Cache-Control header](https://www.varnish-cache.org/lists/pipermail/varnish-commit/2014-April/011269.html), which Drupal 8 has always sent.

**Comment by greg-1-anderson** [comment] 2015-10-16 20:58
This problem should be completely resolved by EOB Monday.

**Comment by greg-1-anderson** [comment] 2015-10-20 17:05
Varnish updates should be rolled out across Pantheon now -- closing.

**Closed by greg-1-anderson** 2015-10-20 17:05 UTC
Labels: platform
