### ISSUE TITLE
Allow Drupal 8 to Cleanly Redirect to Install.php For New Sites

### ISSUE THREAD

**Issue by populist** [pantheon-systems/drops-8#3] opened 2013-09-10 19:56 UTC
There is logic in Drupal 8's _drupal_bootstrap_configuration() which will redirect a user to the install.php file if Drupal is not currently installed. The code looks like this:

if (empty($GLOBALS['databases']) && !drupal_installation_attempted()) {
  include_once __DIR__ . '/install.inc';
  install_goto('core/install.php');
}

The problem is that we inject $GLOBALS['databases'] for all environments (regardless of if Drupal has been installed) which causes this goto logic to fail.

**Comment by greg-1-anderson** [comment] 2015-04-30 20:18
The logic that was in index.php started failing in Drupal 8 beta 10, because it relied on catching an exception when Drupal had not been installed yet.  Unfortunately, shortly before the beta 10 release, something changed in Drupal to cause the pre-installed system to fail with a class not found, which PHP considers to be a fatal error, so no exception is thrown.  I'm not sure why the class cannot be found, as index.php sets up the autoloader first thing.

The failure happens sometime after settings.php is included, so it seems like the best thing to do is to move the logic back to settings.  The test I settled on was to see if the files/css directory already exists.  Prior to installation, files/php already exists, but files/css, files/js, etc. are not created until after the installer runs, so I put in the same redirect code contingent upon this directory not existing.

This is an improvement insofar as we no longer need to customize index.php, but it is a little worse in that (a) the test runs on every request, not just on errors, and (b) if you want to re-install, you must delete files/css in addition to files/php and the database, OR go directly to example.com/core/install.php.

**Comment by greg-1-anderson** [comment] 2015-04-30 22:30
Testing files/css did not work, as the css directory is not created soon enough in the post-install process, so the user kept getting sent to the installer, even after Drupal had been installed.  The files/styles directory is created in time, though, and testing this directory instead works fine, for now.

**Comment by populist** [comment] 2015-05-06 00:41
Great to see. I am going to close this issue because I believe we now have a "clean" (i.e. non core hack) way to do this, although we definitely need to monitor this since it is bound to change.

**Comment by greg-1-anderson** [comment] 2015-08-13 17:46
I'm going to re-open this, because I'm not satisfied with the resolution.  It's fine for the first install, but it is non-intuitive to remove files/styles, and Drupal core's solution -- to expect users to know to go to core/install.php for reinstalls -- as also dissatisfying.

I think a better solution would be to use Drupal 8's [modular exception handling](https://www.drupal.org/node/2331613) to catch the database exception that is thrown when settings provides a database, but the database is empty.

The current symptom is:
```
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db. router' doesn't exist:
```
And then, when Drupal tries to log this message, the same error occurs, recursively:
```
Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.watchdog' doesn't exist:
```
The best place to solve this would be in Drupal core. We could install a listener that caught database exceptions, and redirected to core/install.php if the reported error was 'router' or 'watchdog' table does not exist.  This test should be loose enough to not cause breakage if the order of operations changes slightly in the Drupal bootstrap, but should not be so loose that unrelated "table 'foo' does not exist" errors are not converted into redirects to the installer.

We have some existing issues in Drupal core that are related:

- [Support PHP environment-sourced settings/services/configuration via $_ENV ](https://www.drupal.org/node/1830816)
- [enhance install.php error reporting for the case of an existing settings.php pointing to an empty db](https://www.drupal.org/node/1963208)
- [Make sure install.php gives accurate information if Drupal is already installed](https://www.drupal.org/node/1963760)

None of these are about automatic redirection to core/install.php, though; we should open a new core issue once we have a proposal.

**Comment by greg-1-anderson** [comment] 2015-08-20 17:53
Just a note that we are now getting an error 500 when attempting to redirect to core/install.php (intermittently), as mentioned in #58.

**Comment by greg-1-anderson** [comment] 2015-08-25 22:04
I think the 500 error is unrelated to Drupal 8.

When we fix this issue, we should insure that the `install_display_output()` error is also fixed (#58 closed as a duplicate of this issue.)

**Comment by greg-1-anderson** [comment] 2015-08-26 18:15
As a workaround, if this is not fixed in core, we could wipe the files/css directory in `terminus wipe` or Dashboard wipe.

Also. #58 turned out to be unrelated, and is now fixed.

**Comment by joshkoenig** [comment] 2015-10-27 23:13
Idea from conversation today: could we do a `presssflow_smart_start()` style check of the database in our prepend file (where we've got stuff to connect to the db for healthcheck and heartbeat purposes) and set something like `$_ENV['cms_installed'] = TRUE;` - this would allow a simple tweak in our default `settings.php` to do a redirect to install, rather than a core hack.

**Comment by bthompson-mindgrub** [comment] 2015-11-02 22:44
The `pressflow_smart_start()` style check followed by setting an environment variable seems like a reasonable idea to me.  As it stands currently, anyone who clones a Pantheon D8 site locally using a local dev environment that sets `$_ENV['PANTHEON_ENVIRONMENT']` (namely, Kalabox) is foobar because the git repo doesn't include sites/default/files/styles.

Temporary way around this is to add an `&& $_ENV['PANTHEON_ENVIRONMENT'] != 'kalabox'` to the install check in `settings.php` but I don't think special-casing every provider who injects Pantheon environment variables outside of the Pantheon environment is a scalable solution (or the right solution).

**Comment by greg-1-anderson** [comment] 2015-11-19 18:41
This is now done via a $_SERVER variable set by the platform that indicates whether the database is empty or not.

**Closed by greg-1-anderson** 2015-11-19 18:41 UTC
Labels: core change, minor
