### ISSUE TITLE
Support composer based install

### ISSUE THREAD

**Issue by heddn** [pantheon-systems/drops-8#151] opened 2016-07-14 19:38 UTC
Title says it all.

**Comment by greg-1-anderson** [comment] 2016-10-11 15:30
Duplicate of #152. If you use composer, you will want to use a relocatable docroot. Also, if you relocate your docroot, you will no longer be able to use the Pantheon dashboard to update core, so you're going to want to use composer.

**Closed by greg-1-anderson** 2016-10-11 15:30 UTC
