### ISSUE TITLE
Improve error message presented when installing Drupal 8 in "Git" mode.

### ISSUE THREAD

**Issue by ravindrasingh22** [pantheon-systems/drops-8#78] opened 2015-09-18 06:59 UTC
http://dev-d8-srijan.pantheon.io/core/install.php?langcode=en&profile=standard

Error
Error messageWarning: file_put_contents(sites/default/settings.php): failed to open stream: Permission denied in drupal_rewrite_settings() (line 318 of core/includes/install.inc).
drupal_rewrite_settings(Array)
install_write_profile(Array)
install_run_task(Array, Array)
install_run_tasks(Array)
install_drupal(Object)
The website encountered an unexpected error. Please try again later.
Exception: Failed to modify sites/default/settings.php. Verify the file permissions. in drupal_rewrite_settings() (line 319 of core/includes/install.inc).
drupal_rewrite_settings(Array)
install_write_profile(Array)
install_run_task(Array, Array)
install_run_tasks(Array)
install_drupal(Object)
![screen shot 2015-09-18 at 12 27 35 pm](https://cloud.githubusercontent.com/assets/2268117/9953718/cccc396a-5e00-11e5-9f9b-814a7c383cd3.png)

**Comment by greg-1-anderson** [comment] 2015-09-18 15:20
Go to your site dashboard and set it to SFTP mode.  Then, go back and install your site.

**Comment by greg-1-anderson** [comment] 2015-09-18 15:21
Actually, there should be a way for us to provide a better error message here.  We should do that as a service.

**Comment by stevector** [comment] 2015-10-15 21:45
This issue came up in the Power Users email immediately after Greg announced RC 1 support. Someone at a meetup just ran into it too. Can we bump the priority of resolving this? Even just a message in the dashboard would be helpful.

**Comment by bmackinney** [comment] 2015-10-16 02:38
@stevector we'll have the ability to do it in https://github.com/pantheon-systems/dashboard/pull/988 and then complete it with https://github.com/pantheon-systems/walkme/issues/24

**Comment by greg-1-anderson** [comment] 2015-11-19 18:47
Closing as a duplicate of #36.

**Closed by greg-1-anderson** 2015-11-19 18:47 UTC
Labels: minor

**Comment by pkosenko** [comment] 2017-09-22 23:32
This might be helpful if Pantheon actually HAD a way to set "SFTP Mode".  There is nothing in the Dashboard that suggests ANYTHING about setting GIT vs. SFTP mode.

**Comment by dustinleblanc** [comment] 2017-09-25 13:24
@pkosenko See https://pantheon.io/docs/sftp/ This is and has been a standard feature of the platform for a long time.

**Comment by pkosenko** [comment] 2017-09-27 02:38
I was looking to find someway to access GIT and SFTP mode from one of the main tabs, but those modes are nowhere to be found in the main menus.  I suppose everyone has this problem when they first get into Pantheon, until they poke around and find things.  You have to click on the project to bring up a project pane, which THEN shows GIT/SFTP mode (since they are modes of accessing the project).  Generally one expects things to be available some way through a program's main program tabs.  But those modes are not.

So it was really a MENU issue.  No one was explaining how to GET to the SFTP mode in the posts and I could not find it initially.

**Comment by ari-gold** [comment] 2017-09-27 17:14
@pkosenko Please open up a support chat and we'll be happy to guide you through it.

**Comment by pkosenko** [comment] 2017-09-28 20:24
No need for support chat.  I solved the problem myself when I found the "hidden" SFTP menu item.  It was really just a matter of my not being familiar with the menu structure and having to POKE AROUND.
