### ISSUE TITLE
Drupal 8 reporting "Out of Memory" (probably re-entrant error handler)

### ISSUE THREAD

**Issue by heddn** [pantheon-systems/drops-8#54] opened 2015-08-13 15:27 UTC
I'm consistently receiving this error. The first time was several months ago. But I'm still seeing it today. I mentioned this in passing in #21 in my most recent update.

Allowed memory size of 268435456 bytes exhausted (tried to allocate 265027628 bytes)core/lib/Drupal/Core/Render/BareHtmlPageRenderer.php:70

**Comment by populist** [comment] 2015-08-17 21:53
Are you seeing this error after installation? I can replicate it when you first install a new site, but do not see it afterwards.

**Comment by heddn** [comment] 2015-08-17 22:10
4 months ago it was during the install. And afterwards too in the modules
page. I don't know about anything more recent than that.


Lucas
MTech, LLC <http://www.mtech-llc.com>

**Comment by populist** [comment] 2015-08-17 22:12
Thanks! I think we have tracked this down to a potential screenshot issue when you first install the site (since I can replicate this error when I create a new D8 site but do not go to the URL myself). Needs a bit more investigating.

**Comment by greg-1-anderson** [comment] 2015-10-03 05:21
I just set this to critical, because I can not install Drupal 8.0.0-beta16 due to a reported out-of-memory error on the first page load (after the redirect to core/install.php).

This is partially just Drupal 8; I definitely cannot install D8 on my local machine when I set the memory limit to the advertised 64M. Here are some issues in core related to memory use:

[Determine cause of high memory consumption](https://www.drupal.org/node/2294569)
[Reduce cold cache memory requirements](https://www.drupal.org/node/2494987)

However, I had no trouble installing D8 with a 128M memory limit on my desktop machine, but Pantheon fails to install with a 256M limit.

After more investigation, I am starting to think that this is not an actual out-of-memory situation, but some unrelated error on the Pantheon platform that triggers an out-of-memory error. Perhaps an error handler causes another error to be thrown, and the recursion runs out of memory before stack. Something of that sort; not sure yet.

**Comment by greg-1-anderson** [comment] 2015-10-03 21:31
The out-of-memory error being reported, mentioned above, was caused by missing code that was not committed due to being excluded by our .gitignore.

It is interesting that these error conditions are being reported as "out of memory". I suspect a recursive situation where an error handler is causing an error that is caught by the same handler.  This situation is probably set off by the screenshot utility, as hypothesized above.

**Comment by greg-1-anderson** [comment] 2015-11-19 18:46
Have not seen this in quite a few releases; closing for now. Will re-open if problem manifests again.

**Closed by greg-1-anderson** 2015-11-19 18:46 UTC
Labels: minor

**Comment by matt-cook** [comment] 2015-12-16 22:12
Just in case anyone else arrives here with the same issue I did. I ran into this on Pantheon when I committed code the removed modules without uninstalling first. The solution was to re-add the code for the modules, then uninstall before removing code.

Specifically the errors were (on different sites):

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 219152407 bytes) in /srv/bindings/****/code/core/lib/Drupal/Component/DependencyInjection/Container.php on line 265

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 203685930 bytes) in /srv/bindings/****/code/core/modules/field/src/FieldStorageConfigStorage.php on line 160

(*** mine, unsure security implications).

**Comment by matt-cook** [comment] 2015-12-16 22:38
FWIW, it appears the `memory exhausted` message masks a variety of errors. Triggered it on a page created via page_manager that had the same machine name as a view.
