### ISSUE TITLE
Redirecting to `/core/install.php` from all pages

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/drops-8#81] opened 2015-09-20 15:05 UTC
Likely related to https://github.com/pantheon-systems/drops-8/commit/08dd73ad55cbb8e263f7a3ab333bacb1a159f158

**Comment by greg-1-anderson** [comment] 2015-09-21 16:02
If the change in 08dd73a is causing you to redirect to the installer, then it is working correctly -- the clause it modifies is supposed to redirect you to the installer whenever you are not on an installer page.

There is a separate clause, `!is_dir(__DIR__ . '/files/styles')`, that is used to prevent you from redirecting to the installer once the system is installed.  Do you have a directory at sites/default/files/styles?

Admittedly, this is kind of a crummy test.  Ideally, we would redirect to the installer from the platform, not from code in settings.pantheon.php.

**Comment by greg-1-anderson** [comment] 2015-09-21 16:57
Duplicate of #3.

**Closed by greg-1-anderson** 2015-09-21 16:57 UTC
